# TEMPORARY DEBUG: console logging for tap-hold timing diagnosis. Revert to no.
CONSOLE_ENABLE = yes
KEYCODE_STRING_ENABLE = yes
COMMAND_ENABLE = no
AUDIO_ENABLE = no
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = no
